workflows:
  ios-build:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build the app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      # Example for uploading artifacts to a remote location (like Firebase)
      # Add any publishing steps you need here
      # Example for publishing to TestFlight:
      upload_to_testflight: true
