workflows:
  ios-build:
    name: iOS build
    max_build_duration: 60
    platform: ios
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build the app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      notify:
        email:
          recipients:
            - your-email@example.com
