name: agrive_mart
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.3
  carousel_slider: ^5.0.0
  razorpay_flutter: ^1.2.8
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  http: ^0.13.6
  shared_preferences: ^2.1.1
  pdf: ^3.6.0
  printing: ^5.6.0
  idb_shim: ^2.0.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  badges: ^3.1.2
  provider: ^6.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  google_maps_flutter: ^2.10.0
  flutter_launcher_icons: ^0.14.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.jpg
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.jpg"
